import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0F1115] text-[#EEE]`}
      >
        <div className="min-h-screen font-sans">
          <nav className="p-4 border-b border-white/10">
            <div className="container mx-auto flex justify-between items-center">
              <a href="/" className="font-bold text-lg text-[#FF7A00]">Streakr</a>
              <div className="flex gap-4 items-center">
                <a href="/picks" className="hover:text-[#FF7A00]">Picks</a>
                <a href="/leaderboard" className="hover:text-[#FF7A00]">Leaderboard</a>
                <a href="/faq" className="hover:text-[#FF7A00]">FAQ</a>
                <a href="/rewards" className="hover:text-[#FF7A00]">Rewards</a>
                <a href="/auth" className="rounded-md bg-[#FF7A00] text-black px-3 py-1.5 text-sm font-semibold hover:brightness-110">Sign In</a>
              </div>
            </div>
          </nav>
          <main className="container mx-auto p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
